import Homepage from "@/pages/system/home/Homepage";
import Head from "next/head";
import DownloadApp from "./system/download/downloadApp";


export default function Download() {
  return (
    <div className="text-textColor">
      <Head>
        <title>Download-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DownloadApp />
    </div>
  );
}
