import Homepage from "@/pages/system/home/Homepage";
import Head from "next/head";


export default function Home() {
  return (
    <div className="text-textColor">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
    </div>
  );
}
