import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "@/components/common/Navbar";
import { blogs } from "@/data/Data";
import Headings from "@/components/atoms/Headings";
import { Box, Image, HStack, Text, VStack } from "@chakra-ui/react";

export const Loading = () => {

  return (<div>
    <Head>
      <title>Blog details</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <div>loading ...</div>
  </div>);
};

const Index = () => {
  const router = useRouter();
  const { query, isReady } = useRouter();
  let blogId = router.query.id;
  if (!isReady) {
    return <Loading />;
  }
  let data = blogs[blogId];
  return ( 
    <div>
      <Head>
        <title>Blog details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box 
        px={{ base: 20 }}
      >
        <Box>
          <Image src={data.blogImg} alt={"blog-image"} w={"100%"} h={"450px"} borderRadius={"20px"} />
        </Box>
        <HStack fontSize={"14px"} spacing={3} fontWeight={"medium"} py={8}>
          <Text >
            {data.date}
          </Text>
          <Text fontWeight={"extrabold"} fontSize={"20px"}>.</Text>
          <Text>
            {data.readTime}
          </Text>
        </HStack>
        
        <Headings color={"red.900"} headingWidth={"100%"} fontSize={"48px"}  py={10} headingText={data.blogTitle}/>
        <Box>
          <HStack>
            <VStack>

            </VStack>
            <VStack>
              
            </VStack>
          </HStack>
        </Box>
      </Box>
    </div>
  );
};
 
export default Index;